### PR TITLE
feature!: remove license from generated manifest

### PR DESCRIPTION
**Pull request by hutnikau**

### CODE REVIEW

**Review by gitromba — CHANGES_REQUESTED** [review]
@hutnikau are we not interested in the extension licensing anymore? 

[Unit tests are failing](http://qa.kitchen.it.taocloud.org/blue/organizations/jenkins/ci-pipeline-cg-extension-pr%2Fextension-tao-devtools/detail/PR-189/1/pipeline/104) 😞

**Comment by hutnikau** [comment]
> @hutnikau are we not interested in the extension licensing anymore?
> 
> [Unit tests are failing](http://qa.kitchen.it.taocloud.org/blue/organizations/jenkins/ci-pipeline-cg-extension-pr%2Fextension-tao-devtools/detail/PR-189/1/pipeline/104) 😞

License is in composer.json file. Does not make sense to duplicate it.

**Comment by gitromba** [comment]
> > @hutnikau are we not interested in the extension licensing anymore?
> > [Unit tests are failing](http://qa.kitchen.it.taocloud.org/blue/organizations/jenkins/ci-pipeline-cg-extension-pr%2Fextension-tao-devtools/detail/PR-189/1/pipeline/104) 😞
> 
> License is in composer.json file. Does not make sense to duplicate it.

Should be someone be notified from product from development/customer relation as this PR is about to introduce changes in an existing TAO feature?

**Review by Haru0 — APPROVED** [review]
Extensions manager is back and running. I see nothing suspicious but failing tests.

**Pull request merged**
